name: fine_cut
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.39
  intl: ^0.20.2
  dropdown_search: ^6.0.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
